name = "dom"
version = "0.1.0"

[ source ]
owner = "stefan-hoeck"
repo = "idris2-dom"
rev = "793a012645ac07e1929603bb95d9b8a69640808e"
sha256 = "bCq45qy18ggpBiEQ3zbx98Am/ODCRspa4K1gc347MOs="

[ depends ]
idrisLibs = [ "sop", "experimental" ]
