name = "elab-util"
version = "0.3.1"

[ source ]
owner = "stefan-hoeck"
repo = "idris2-elab-util"
rev = "ccd299b776a16b3f0f572b4692e419bd58df6278"
sha256 = "Wmwk47Ko1xl+oX146U7OnDK3M1pai2ccxdnzeE+Do/U="
