name = "hedgehog"
version = "0.1.0"

[ source ]
owner = "stefan-hoeck"
repo = "idris2-hedgehog"
rev = "e48a6a16156ceb9cd2a92d796cdafbf2a3520702"
sha256 = "9uqFKqpA3oQJhEnnJDwG2etsNP5PPXe/JR0h/2yPZLE="

[ depends ]
idrisLibs = [ "elab-util", "sop", "pretty-show" ]
