name = "hedgehog"
version = "0.5.0"

[ source ]
owner = "stefan-hoeck"
repo = "idris2-hedgehog"
rev = "v0.5.0"
sha256 = "0P8MJiQjytAddmmsYmrm4fFhCybSGi9mlLfQKeDHpZo="

[ depends ]
idrisLibs = [ "elab-util", "sop", "pretty-show" ]
