name = "lsp"
version = "0.4.0"
executable = "idris2-lsp"

[ source ]
owner = "idris-community"
repo = "idris2-lsp"
rev = "9be436dcc26ab60c5b3a5f2c07cb1d051353e629"
sha256 = "5ovOehyEh3RMEp2lbjv71sGaKI+VaNgt7WhORIDVyXU="

[ depends ]
idrisLibs = [ "idris2api" ]
buildInputs = [ ]

[ test ]
enable = true
preTest = """
# macOS does not allow direct access to /tmp
for file in tests/Makefile tests/lsp/message001/*; do
  sed -i "s|/tmp/test-lsp.idr|$(pwd)/tests/test-lsp.idr|g" $file;
done

make -C tests testbin
"""
command = "make -C tests INTERACTIVE= "
