name = "pretty-show"
version = "0.3.0"

[ source ]
owner = "stefan-hoeck"
repo = "idris2-pretty-show"
rev = "ba1d51ba76edd28d67fa616a8bc029be1989db50"
sha256 = "obopOd3PkbIglgXVmNAthXK0bu4Po4QJCwvzNSB1OYc="

[ depends ]
idrisLibs = [ "elab-util", "sop" ]

[ test ]
enable = true
command = """
idris2 --build test.ipkg
build/exec/runTest
"""
