name = "pretty-show"
version = "0.5.0"

[ source ]
owner = "stefan-hoeck"
repo = "idris2-pretty-show"
rev = "4f6beeca0f1899bc8fcf2fe979ea293c00e466f8"
sha256 = "MK+RnV5VGRY3eNI+iBcZzi3r2rSc/utpF5Taaj2W/a8="

[ depends ]
idrisLibs = [ "elab-util", "sop" ]

[ test ]
enable = true
command = """
idris2 --build test.ipkg
build/exec/runTest
"""
