name: "macOS"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v14.1
      with:
        nix-path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: cm-idris2-pkgs
        authToken : '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build
    - run: nix-build all-drvs.nix
